default:
  image: node:16.16.0

stages:
  - security
  - deploy

variables:
  NODE_ENV: 'production'

cache:
  paths:
    - node_modules/

sast:
  stage: security
  only:
    refs:
      - dev
  artifacts:
    reports:
      sast: gl-sast-report.json
  script:
    - echo "Running SAST scan"
  allow_failure: true

include:
  - template: Security/SAST.gitlab-ci.yml



#####################################################################
# COMMON PIPELINE
#####################################################################

deploy_production:
  stage: deploy
  only:
    refs:
      - main
  when: manual
  script:
    - npm install -g vercel@latest
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
