default:
  image: node:16.16.0

stages:
  - deploy
  - verify_job

variables:
  NODE_ENV: 'production'

cache:
  paths:
    - node_modules/
verify_job:
  script:
    - echo "VERCEL_TOKEN is ${VERCEL_TOKEN:+set}"  # This will print "set" if the variable exists and is non-empty
    - npm install -g vercel@latest
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID

deploy_production:
  stage: deploy
  only:
    refs:
      - main
  when: manual
  script:
    - npm install -g vercel@latest
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
