version: "3.9"
services:
  faith-db:
    container_name: faith-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: faith_next_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: faith_next_db
      PGDATA: /var/lib/postgresql/faith-next-server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U faith_next_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - ~/.faith:/var/lib/postgresql
    ports:
      - "5432:5432"

  faith-mail:
    container_name: faith-mail
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
