version: "3.9"
services:
  hedgepulse-db:
    container_name: hedgepulse-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hedgepulse_next_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hedgepulse_next_db
      PGDATA: /var/lib/postgresql/faith-next-server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hedgepulse_next_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - ~/.hedge:/var/lib/postgresql
    ports:
      - "5432:5432"

  hedgepulse-mail:
    container_name: hedgepulse-mail
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
